### ISSUE TITLE
Columns  not show

### ISSUE THREAD

**Issue by snifferchess** [Arthur-Milchior/anki-link-to-open-browser#7]
for me not show columns Card ID and Note ID

**Comment by Arthur-Milchior** [comment]
Sorry but I've no idea what you mean here. I need far more detail and explanation

**Comment by snifferchess** [comment]
Thank for u answer
[image: image.png]


Em ter., 25 de ago. de 2020 às 09:57, Arthur Milchior <
notifications@github.com> escreveu:

**Comment by Arthur-Milchior** [comment]
Sorry, there is no image here. You probably need to use the website of github directly to show the image https://github.com/Arthur-Milchior/anki-link-to-open-browser/issues/7

**Comment by snifferchess** [comment]
Sorry

![image](https://user-images.githubusercontent.com/12069641/91186062-f664c880-e6c4-11ea-86cd-fc17883792e1.png)

**Comment by Arthur-Milchior** [comment]
You probably don't have the advanced browser, as explained on https://github.com/Arthur-Milchior/anki-link-to-open-browser

**Comment by snifferchess** [comment]
I have 

![image](https://user-images.githubusercontent.com/12069641/91191449-2fa03700-e6cb-11ea-89f4-0e35c90921c6.png)

**Comment by Arthur-Milchior** [comment]
Then please open a bug with Advanced Browse's github because I can't help here

**Comment by snifferchess** [comment]
Ok,  thank you
